// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_AhP713X873WfJd8X6JCQ6d2eu-LVh4',
    appId: '1:524256179554:web:c52457f6cc70f32b38a83b',
    messagingSenderId: '524256179554',
    projectId: 'push-notificaciones-e7d9e',
    authDomain: 'push-notificaciones-e7d9e.firebaseapp.com',
    storageBucket: 'push-notificaciones-e7d9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIr7oE6QsqIPy2DPBOD2LMjY5ts1Rx2K8',
    appId: '1:524256179554:android:ba945c57efe3e0de38a83b',
    messagingSenderId: '524256179554',
    projectId: 'push-notificaciones-e7d9e',
    storageBucket: 'push-notificaciones-e7d9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ociH3tbwurD9VIEzq637qpiW19i8wCo',
    appId: '1:524256179554:ios:074095a07bae629f38a83b',
    messagingSenderId: '524256179554',
    projectId: 'push-notificaciones-e7d9e',
    storageBucket: 'push-notificaciones-e7d9e.appspot.com',
    iosBundleId: 'com.dcopxss.pushNoptification',
  );
}
